apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: the-farmer
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for the the-farmer applications.
  # Allow manifests to deploy from any Git repos inside the the-farmer-trading organization on github.
  sourceRepos:
  - 'https://github.com/the-farmer-trading/*'
  # Only permit applications to deploy to the the-farmer namespace in the same cluster
  destinations:
  - namespace: the-farmer
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to the the-farmer project.
    policies:
    - p, proj:the-farmer:read-only, applications, get, the-farmer/*, allow