apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-credentials
  namespace: the-farmer
spec:
  encryptedData:
    .dockerconfigjson: AgCdlNe6dYQQYRJZGGa0ZqmLLplepnpBF+2NTfeeYROLlcFSpQ+xnoROQRBaYSGja/m8S2Afx6m/Fm0l+NiVsladoSxngmRaUX0KXc1ZdCItKsJt6T3idyVPlhgagIYzF4GZF2MD0D+rIH+ZtwivWouEGRz+xNIh7TY0Iueqxnapow0OyLhAPVjttfFJUG++G2VlWhfDDXHJcyZBgarxHYzuA7/h7SscmiLhV8TPNl9PB0IsyLTr2dBpHpjA3lyYs31n1/fa0GykmvEmW9j2W8iv6qRW6Xh/q5M+NAymzutJpWQwGlrAbIIN/DZYfLGAqk6eBI66AMJ5qKUWuB6jP28BIno+4t5Sj1A2wr0ClhjFkBAjtpGjJPTfaBFRTePfkH6hNnTU0IbNIte9ZIoM8pOMIOykukN+1PEjO1RsZmZJz4EdxhH58JZRJ6N4VNx9NZs3+rUkJ/CEVD30FM4NlZIr3ItB0AGwWOIfMXRp94e9ocFS+kGdieYEusP2b66br066SIiDy6mKTGfoiCFFTlb3y57/5cYXY+VY3ZdXwzNl93RRIvDZ/ZAhqVtDUhPHLBHK78g+1VuwNbrrO3wf7H0YQs8+TWSn9b7ZzK5FlMPfgJdSV7XSa6UXPA7qJMzQP0kdpFyMkMSPYeVAQK8ify7z+0RMwazO6SkCAN3C+43K4n+dy2TZgNrkOah+bovOaPN5yFhTPJsPEj3diOBVTTmcxOXhhfWv+RkBP3C/iACthy142amKw0C8Pfo1egNxu5/tF5tnQm/wIn7kp99LkczvL6ZfDi7Ym19CHryQ5gYH5gW3XD6OKcoOuMcyU9kx5cSDvg8xjNIkFjtJmA2eRB8je63eBb7Q9BkJLBWUERxU037V/XAaUEZj1dwCv0TCzsbMG7U4VZTRHlbUxJV2St43w7JDegmsimw05k3ATOkBMVIx9k2hrUZDE8CGeOHs/VZdgA==
  template:
    metadata:
      creationTimestamp: null
      name: artifactory-credentials
      namespace: the-farmer
    type: kubernetes.io/dockerconfigjson

