apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: artifactory-credentials
    creationPolicy: Owner
  data:
  - secretKey: dockerconfigjson
    remoteRef:
      key: the-farmer_artifactory_dockerconfigjson