apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials-the-farmer
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: artifactory-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: the-farmer_github_username
  - secretKey: password
    remoteRef:
      key: the-farmer_github_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-credentials-the-farmer
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-credentials-the-farmer
    app.kubernetes.io/part-of: argocd
data:
  repository.credentials: |
    - url: https://github.com/the-farmer-trading
      passwordSecret:
        name: github-credentials-the-farmer
        key: password
      usernameSecret:
        name: github-credentials-the-farmer
        key: username